######################################################################
# Automatically generated by qmake (3.1) Wed Sep 2 18:44:19 2020
######################################################################
include(../stub_linux/stub.pri)
TEMPLATE = app
TARGET = ut_screen_shot_recorder
INCLUDEPATH += .

QT += core gui testlib

QT += core
QT += widgets
QT += gui
QT += network
QT += x11extras
QT += dbus
QT += multimedia
QT += multimediawidgets
QT += concurrent
LIBS += -lX11 -lXext -lXtst -lXfixes -lXcursor -lgtest
LIBS += -L"libprocps" -lprocps

CONFIG += link_pkgconfig
CONFIG += c++11
PKGCONFIG += dtkgui dtkwidget xcb xcb-util dframeworkdbus


RESOURCES = ../../deepin-screen-recorder.qrc \
    ../widgets/resources.qrc \
    ../icons/icons.qrc

QMAKE_CXXFLAGS += -g
QMAKE_CXXFLAGS += -Wno-error=deprecated-declarations -Wno-deprecated-declarations


QMAKE_CXXFLAGS += -g -Wall -fprofile-arcs -ftest-coverage -O0
QMAKE_LFLAGS += -g -Wall -fprofile-arcs -ftest-coverage  -O0


#DEFINES += TSAN #互斥
contains(DEFINES,TSAN){
   QMAKE_CXXFLAGS+="-fsanitize=thread"
   QMAKE_CFLAGS+="-fsanitize=thread"
   QMAKE_LFLAGS+="-fsanitize=thread"
}
else{
   QMAKE_CXXFLAGS+="-fsanitize=undefined,address,leak -fno-omit-frame-pointer"
   QMAKE_CFLAGS+="-fsanitize=undefined,address,leak -fno-omit-frame-pointer"
   QMAKE_LFLAGS+="-fsanitize=undefined,address,leak -fno-omit-frame-pointer"
}

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += test_all_interfaces.h \
           ut_button_feedback.h \
           ut_countdown_tooltip.h \
           ut_main_window.h \
           ut_process_tree.h \
           ut_record_process.h \
           ut_RecorderRegionShow.h \
           ut_screenshot.h \
           ut_settings.h \
           ut_show_buttons.h \
           ut_utils.h \
           dbusinterface/ut_dbusnotify.h \
           menucontroller/ut_menucontroller.h \
           utils/ut_audioutils.h \
           utils/ut_baseutils.h \
           utils/ut_calculaterect.h \
           utils/ut_configsettings.h \
           utils/ut_dbusutils.h \
           utils/ut_desktopinfo.h \
           utils/ut_screengrabber.h \
           utils/ut_shortcut.h \
           utils/ut_tempfile.h \
           utils/ut_utils_other.h \
           widgets/ut_colortoolwidget.h \
           widgets/ut_keybuttonwidget.h \
           widgets/ut_maintoolwidget.h \
           widgets/ut_zoomIndicator.h\
        ../utils/audioutils.h \
        ../utils/baseutils.h \
        ../utils/calculaterect.h \
        ../utils/configsettings.h \
        ../utils/dbusutils.h \
        ../utils/desktopinfo.h \
        ../utils/screengrabber.h \
        ../utils/shortcut.h \
        ../utils/tempfile.h \
        ../utils/shapesutils.h \
        ../utils/camerawatcher.h \
        ../utils/voicevolumewatcher.h \
        ../widgets/colortoolwidget.h \
        ../widgets/keybuttonwidget.h \
        ../widgets/maintoolwidget.h \
        ../widgets/zoomIndicator.h \
        ../widgets/filter.h \
        ../widgets/tooltips.h \
        ../widgets/sidebar.h \
        ../widgets/toolbar.h \
        ../widgets/subtoolwidget.h \
        ../widgets/camerawidget.h \
        ../widgets/toptips.h \
        ../widgets/shapeswidget.h \
        ../widgets/textedit.h \
        ../widgets/shottoolwidget.h \
        ../widgets/toolbutton.h \
        ../menucontroller/menucontroller.h \
        ../dbusinterface/dbusnotify.h \
        ../constant.h \
        ../utils.h \
        ../button_feedback.h \
        ../countdown_tooltip.h \
        ../main_window.h \
        ../record_process.h \
        ../RecorderRegionShow.h \
        ../screenshot.h \
        ../settings.h \
        ../show_buttons.h \
        ../process_tree.h \
        ../screen_shot_event.h \
        ../event_monitor.h \
        ../lib/GifH/gif.h \
        ../xgifrecord.h


SOURCES += main.cpp \
    ../utils/audioutils.cpp \
    ../utils/baseutils.cpp \
    ../utils/calculaterect.cpp \
    ../utils/configsettings.cpp \
    ../utils/dbusutils.cpp \
    ../utils/desktopinfo.cpp \
    ../utils/screengrabber.cpp \
    ../utils/shortcut.cpp \
    ../utils/tempfile.cpp \
    ../utils/shapesutils.cpp \
    ../utils/camerawatcher.cpp \
    ../utils/voicevolumewatcher.cpp \
    ../widgets/colortoolwidget.cpp \
    ../widgets/keybuttonwidget.cpp \
    ../widgets/maintoolwidget.cpp \
    ../widgets/zoomIndicator.cpp \
    ../widgets/filter.cpp \
    ../widgets/tooltips.cpp \
    ../widgets/sidebar.cpp \
    ../widgets/toolbar.cpp \
    ../widgets/subtoolwidget.cpp \
    ../widgets/camerawidget.cpp \
    ../widgets/toptips.cpp \
    ../widgets/shapeswidget.cpp \
    ../widgets/textedit.cpp \
    ../widgets/shottoolwidget.cpp \
    ../menucontroller/menucontroller.cpp \
    ../dbusinterface/dbusnotify.cpp \
    ../constant.cpp \
    ../utils.cpp \
    ../button_feedback.cpp \
    ../countdown_tooltip.cpp \
    ../main_window.cpp \
    ../record_process.cpp \
    ../RecorderRegionShow.cpp \
    ../screenshot.cpp \
    ../settings.cpp \
    ../show_buttons.cpp \
    ../process_tree.cpp \
    ../screen_shot_event.cpp \
    ../event_monitor.cpp \
    ../xgifrecord.cpp
