/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p recordiconwidget_interface -c recordiconwidget_interface ./com.deepin.dde.daemon.Dock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "recordiconwidget_interface.h"
#include "../../utils/log.h"

// 添加序列化实现
QDBusArgument &operator<<(QDBusArgument &argument, const DockRect &rect)
{
    argument.beginStructure();
    argument << rect.x << rect.y << rect.width << rect.height;
    argument.endStructure();
    return argument;
}

const QDBusArgument &operator>>(const QDBusArgument &argument, DockRect &rect)
{
    argument.beginStructure();
    argument >> rect.x >> rect.y >> rect.width >> rect.height;
    argument.endStructure();
    return argument;
}

/*
 * Implementation of interface class recordiconwidget_interface
 */

recordiconwidget_interface::recordiconwidget_interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qCDebug(dsrApp) << "recordiconwidget_interface constructor called for service:" << service << ", path:" << path;
    qDBusRegisterMetaType<DockRect>();
    qCDebug(dsrApp) << "DockRect meta type registered.";
}

recordiconwidget_interface::~recordiconwidget_interface()
{
    qCDebug(dsrApp) << "recordiconwidget_interface destructor called.";
}

