/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p iconwidget_interface -c iconwidget_interface ./com.deepin.dde.daemon.Dock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "iconwidget_interface.h"
#include "../../utils/log.h"

/*
 * Implementation of interface class iconwidget_interface
 */

iconwidget_interface::iconwidget_interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qCDebug(dsrApp) << "iconwidget_interface constructor called for service:" << service << "path:" << path;
}

iconwidget_interface::~iconwidget_interface()
{
    qCDebug(dsrApp) << "iconwidget_interface destructor called.";
}

