/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p timewidget_interface -c timewidget_interface ./org.deepin.dde.daemon.Dock1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "timewidget_interface.h"
#include "../../utils/log.h"

/*
 * Implementation of interface class timewidget_interface
 */

timewidget_interface::timewidget_interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qCDebug(dsrApp) << "timewidget_interface constructor called for service:" << service << "path:" << path;
}

timewidget_interface::~timewidget_interface()
{
    qCDebug(dsrApp) << "timewidget_interface destructor called.";
}

