#!/bin/bash
if qdbus --literal com.deepin.daemon.Keybinding /com/deepin/daemon/Keybinding com.deepin.daemon.Keybinding.CheckAvaliable "<Control><Alt>R"|grep false
then
    echo "shortcut in use"
    json_output=`qdbus --literal com.deepin.daemon.Keybinding /com/deepin/daemon/Keybinding com.deepin.daemon.Keybinding.CheckAvaliable "<Control><Alt>R"|grep Type|sed 's/^"//g' | sed 's/"$//g'`
    id=`echo $json_output |sed -n 's|.*"Id":"\([^"]*\)".*|\1|p'`
    type=`echo $json_output |sed -n 's|.*"Type":\([^,]*\).*|\1|p'`
    name=`echo $json_output |sed -n 's|.*"Name":"\([^"]*\)".*|\1|p'`
    shortcut_name="Deepin Screen Recorder"
    if [ "${name}" == "$shortcut_name" ]
    then
        qdbus --literal com.deepin.daemon.Keybinding /com/deepin/daemon/Keybinding com.deepin.daemon.Keybinding.Delete ${id} $type
    else
        echo "shortcut is in other use"
    fi
else
    echo "shortcut not in use"
fi
