/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p voicevolumewatcher_interface -c voicevolumewatcher_interface -i audioutils.h ./com.deepin.daemon.Audio.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "voicevolumewatcher_interface.h"
#include "utils/log.h"

/*
 * Implementation of interface class voicevolumewatcher_interface
 */

voicevolumewatcher_interface::voicevolumewatcher_interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qCDebug(dsrApp) << Q_FUNC_INFO << "voicevolumewatcher_interface initialized for service:" << service << ", path:" << path;
}

voicevolumewatcher_interface::~voicevolumewatcher_interface()
{
    qCDebug(dsrApp) << Q_FUNC_INFO << "voicevolumewatcher_interface destructor called.";
}

