// SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This translation unit uses #define private public to access the private
// static handle_* dispatchers generated by qtwaylandscanner.
// All Qt/system headers are included first, then the macro is defined,
// so only the project's own protocol headers are affected.

#include <gtest/gtest.h>
#include <wayland-client-core.h>
#include <dlfcn.h>

// All system headers are now processed. Safe to redefine.
#define private public
#define protected public

#include "stub.h"
#include "addr_pri.h"

#include "../../src/protocols/ext-image-copy-capture/qwayland-ext-image-copy-capture-v1.h"
#include "../../src/protocols/ext-image-copy-capture/qwayland-ext-foreign-toplevel-list-v1.h"
#include "../../src/protocols/ext-image-copy-capture/qwayland-ext-image-capture-source-v1.h"
#include "../../src/protocols/linux-dmabuf/qwayland-linux-dmabuf-unstable-v1.h"
#include "../../src/qwayland-treeland-capture-unstable-v1.h"

// Public subclasses so `data` arg can be the C++ object
class FullCovIccSession : public QtWayland::ext_image_copy_capture_session_v1 {};
class FullCovIccFrame   : public QtWayland::ext_image_copy_capture_frame_v1 {};
class FullCovIccCursor  : public QtWayland::ext_image_copy_capture_cursor_session_v1 {};
class FullCovFtl        : public QtWayland::ext_foreign_toplevel_list_v1 {};
class FullCovFth        : public QtWayland::ext_foreign_toplevel_handle_v1 {};
class FullCovDmabuf     : public QtWayland::zwp_linux_dmabuf_v1 {};
class FullCovDmabufParams : public QtWayland::zwp_linux_buffer_params_v1 {};
class FullCovDmabufFb   : public QtWayland::zwp_linux_dmabuf_feedback_v1 {};
class FullCovTlSession  : public QtWayland::treeland_capture_session_v1 {};
class FullCovTlFrame    : public QtWayland::treeland_capture_frame_v1 {};
class FullCovTlContext  : public QtWayland::treeland_capture_context_v1 {};

using namespace testing;

// ============================================================
// Private static handle_* dispatchers — now public via #define
// ============================================================

TEST(ProtocolsHandleCovTest, IccSessionHandlers)
{
    FullCovIccSession s; void *d = &s; wl_array arr{};
    QtWayland::ext_image_copy_capture_session_v1::handle_buffer_size(d, nullptr, 0, 0);
    QtWayland::ext_image_copy_capture_session_v1::handle_shm_format(d, nullptr, 0);
    QtWayland::ext_image_copy_capture_session_v1::handle_dmabuf_device(d, nullptr, &arr);
    QtWayland::ext_image_copy_capture_session_v1::handle_dmabuf_format(d, nullptr, 0, &arr);
    QtWayland::ext_image_copy_capture_session_v1::handle_done(d, nullptr);
    QtWayland::ext_image_copy_capture_session_v1::handle_stopped(d, nullptr);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, IccFrameHandlers)
{
    FullCovIccFrame f; void *d = &f;
    QtWayland::ext_image_copy_capture_frame_v1::handle_transform(d, nullptr, 0);
    QtWayland::ext_image_copy_capture_frame_v1::handle_damage(d, nullptr, 0, 0, 0, 0);
    QtWayland::ext_image_copy_capture_frame_v1::handle_presentation_time(d, nullptr, 0, 0, 0);
    QtWayland::ext_image_copy_capture_frame_v1::handle_ready(d, nullptr);
    QtWayland::ext_image_copy_capture_frame_v1::handle_failed(d, nullptr, 0);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, IccCursorHandlers)
{
    FullCovIccCursor c; void *d = &c;
    QtWayland::ext_image_copy_capture_cursor_session_v1::handle_enter(d, nullptr);
    QtWayland::ext_image_copy_capture_cursor_session_v1::handle_leave(d, nullptr);
    QtWayland::ext_image_copy_capture_cursor_session_v1::handle_position(d, nullptr, 0, 0);
    QtWayland::ext_image_copy_capture_cursor_session_v1::handle_hotspot(d, nullptr, 0, 0);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, ForeignListHandlers)
{
    FullCovFtl l; void *d = &l;
    QtWayland::ext_foreign_toplevel_list_v1::handle_toplevel(d, nullptr, nullptr);
    QtWayland::ext_foreign_toplevel_list_v1::handle_finished(d, nullptr);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, ForeignHandleHandlers)
{
    FullCovFth h; void *d = &h;
    QtWayland::ext_foreign_toplevel_handle_v1::handle_closed(d, nullptr);
    QtWayland::ext_foreign_toplevel_handle_v1::handle_done(d, nullptr);
    QtWayland::ext_foreign_toplevel_handle_v1::handle_title(d, nullptr, "t");
    QtWayland::ext_foreign_toplevel_handle_v1::handle_app_id(d, nullptr, "a");
    QtWayland::ext_foreign_toplevel_handle_v1::handle_identifier(d, nullptr, "i");
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, DmabufHandlers)
{
    FullCovDmabuf d2; void *d = &d2;
    QtWayland::zwp_linux_dmabuf_v1::handle_format(d, nullptr, 0);
    QtWayland::zwp_linux_dmabuf_v1::handle_modifier(d, nullptr, 0, 0, 0);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, DmabufParamsHandlers)
{
    FullCovDmabufParams p; void *d = &p;
    QtWayland::zwp_linux_buffer_params_v1::handle_created(d, nullptr, nullptr);
    QtWayland::zwp_linux_buffer_params_v1::handle_failed(d, nullptr);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, DmabufFeedbackHandlers)
{
    FullCovDmabufFb fb; void *d = &fb;
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_done(d, nullptr);
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_format_table(d, nullptr, 0, 0);
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_main_device(d, nullptr, nullptr);
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_tranche_done(d, nullptr);
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_tranche_target_device(d, nullptr, nullptr);
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_tranche_formats(d, nullptr, nullptr);
    QtWayland::zwp_linux_dmabuf_feedback_v1::handle_tranche_flags(d, nullptr, 0);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, TreelandSessionHandlers)
{
    FullCovTlSession s; void *d = &s;
    QtWayland::treeland_capture_session_v1::handle_frame(d, nullptr, 0,0,0,0,0,0,0,0,0,0);
    QtWayland::treeland_capture_session_v1::handle_object(d, nullptr, 0,0,0,0,0,0);
    QtWayland::treeland_capture_session_v1::handle_ready(d, nullptr, 0,0,0);
    QtWayland::treeland_capture_session_v1::handle_cancel(d, nullptr, 0);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, TreelandFrameHandlers)
{
    FullCovTlFrame f; void *d = &f;
    QtWayland::treeland_capture_frame_v1::handle_buffer(d, nullptr, 0,0,0,0);
    QtWayland::treeland_capture_frame_v1::handle_buffer_done(d, nullptr);
    QtWayland::treeland_capture_frame_v1::handle_flags(d, nullptr, 0);
    QtWayland::treeland_capture_frame_v1::handle_ready(d, nullptr);
    QtWayland::treeland_capture_frame_v1::handle_failed(d, nullptr);
    SUCCEED();
}

TEST(ProtocolsHandleCovTest, TreelandContextHandlers)
{
    FullCovTlContext c; void *d = &c;
    QtWayland::treeland_capture_context_v1::handle_source_ready(d, nullptr, 0,0,0,0,0);
    QtWayland::treeland_capture_context_v1::handle_source_failed(d, nullptr, 0);
    SUCCEED();
}
