// SPDX-FileCopyrightText: 2022-2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once
//#include "waylandrecord/ut_avinputstream.h"
//#include "waylandrecord/ut_avoutputstream.h"
//#include "waylandrecord/ut_recordadmin.h"
//#include "waylandrecord/ut_waylandintegration.h"
//#include "waylandrecord/ut_waylandintegration_p.h"
//#include "waylandrecord/ut_writeframethread.h"
//#include "widgets/ut_shapeswidget.h" // API drift: paintRect/paintEllipse
// signatures now take an extra `int radius`, paintText is overloaded, and the
// test references a non-existent Toolshape::isStraight field. Re-enable after
// updating the ACCESS_PRIVATE_FUN signatures and Toolshape fields in the test.
#include "ut_main_window.h"
#include "utils/ut_pixmergethread.h"
#include "utils/ut_scrollScreenshot.h"
#include "utils/ut_audioutils.h"
#include "utils/ut_baseutils.h"
#include "utils/ut_configsettings.h"
//#include "utils/ut_desktopinfo.h"
#include "utils/ut_screengrabber.h"
#include "utils/ut_shortcut.h"
#include "utils/ut_tempfile.h"
#include "utils/ut_utils_other.h"
#include "utils/ut_calculaterect.h"
#include "widgets/ut_keybuttonwidget.h"
#include "widgets/ut_colortoolwidget.h"
#include "widgets/ut_maintoolwidget.h"
#include "widgets/ut_zoomIndicator.h"
#include "menucontroller/ut_menucontroller.h"
#include "dbusinterface/ut_dbusnotify.h"
#include "dbusinterface/ut_ocrinterface.h"
//#include "ut_RecorderRegionShow.h" // CameraWidget::initCamera removed, getcameraStatus renamed to getCameraStatus, cameraStart return-type changed
#include "ut_countdown_tooltip.h"
#include "ut_settings.h"
#include "ut_show_buttons.h"
#include "ut_utils.h"
#include "ut_button_feedback.h"
#include "ut_record_process.h"
#include "ut_screenshot.h"
#include "utils/ut_voiceVolumeWatcher.h"
//#include "utils/ut_WaylandScrollMonitor.h" // WaylandScrollMonitor class is KF5_WAYLAND_FLAGE_ON-gated; disabled with that macro
//#include "widgets/ut_shapeswidget.h"
#include "widgets/ut_toptips.h"
//#include "widgets/ut_camerawidget.h" // CameraWidget: many renamed/removed members (initCamera, cameraResume, captureImage, getcameraStatus->getCameraStatus, ...)
//#include "widgets/ut_tooltips.h" // ToolTips enterEvent signature changed (addr_pri ambiguity)
#include "widgets/ut_textedit.h"
//#include "widgets/ut_shottoolwidget.h" // ShotToolWidget ctor/initRectLabel/m_blurRectButton/... drift
//#include "widgets/ut_subtoolwidget.h" // SubToolWidget API drift
#include "widgets/ut_hoverfilter.h"
#include "widgets/ut_hintfilter.h"
#include "widgets/ut_hovershadowfilter.h"
#include "widgets/ut_hintfilterprivate.h"
//#include "widgets/ut_toolbutton.h" // ToolButton setTips/getTips removed; enterEvent QEvent->QEnterEvent
//#include "widgets/ut_toolbarwidget.h" // ToolBarWidget setExpand/changeArrowAndLineFromBar/... drift
//#include "widgets/ut_toolbar.h"
//#include "widgets/ut_sidebar.h" // SideBar initSideBar removed; enterEvent QEvent->QEnterEvent
//#include "widgets/ut_sidebarwidget.h" // SideBarWidget ctor signature changed
#include "widgets/ut_scrollshottip.h"
#include "ext-image-capture/ut_extcaptureframebuffer.h"
#include "ext-image-capture/ut_multiscreenframecompositor.h"
#include "ext-image-capture/ut_extcapturerecorder.h"
#include "ext-image-capture/ut_extcapturebridge.h"
#include "ext-image-capture/ut_extcaptureframe.h"
#include "ext-image-capture/ut_extcaptureintegration.h"
#include "ext-image-capture/ut_extcapturesession.h"
#include "ext-image-capture/ut_multiscreencapturecoordinator.h"
#include "gstrecord/ut_gstinterface.h"
#include "utils/ut_borderprocessinterface.h"
#include "ut_event_monitor.h"
#include "widgets/ut_shapeswidget_ext.h"
#include "widgets/ut_shapeswidget_ext2.h"
#include "widgets/ut_shapeswidget_geo.h"
#include "widgets/ut_shapeswidget_paint_cov.h"
#include "utils/ut_calculaterect_ext.h"
#include "utils/ut_screengrabber_ext.h"
#include "ut_utils_ext.h"
#include "widgets/ut_toolbutton_ext.h"
#include "widgets/ut_camerawidget_ext.h"
#include "widgets/ut_sidebar_ext.h"
#include "ut_RecorderRegionShow_ext.h"
#include "ext-image-capture/ut_extcapturerecorder_ext.h"
#include "ext-image-capture/ut_multiscreencapturecoordinator_ext.h"
#include "ext-image-capture/ut_extcaptureframe_ext.h"
#include "widgets/ut_savemenumanager_ext.h"
#include "widgets/ut_savebutton_ext.h"
#include "widgets/ut_shapetoolwidget.h"
#include "gstrecord/ut_gstrecordx_ext.h"
#include "gstrecord/ut_gstrecordx_x11_cov.h"
#include "ut_record_process_ext.h"
#include "widgets/ut_subtoolwidget_ext.h"
#include "widgets/ut_imagemenu_ext.h"
#include "ut_main_window_ext.h"
#include "ut_main_window_ef.h"
#include "ut_main_window_cov.h"
#include "ut_main_window_ef_state_cov.h"
#include "ut_main_window_cov4.h"
#include "ut_main_window_cov5.h"
#include "ut_dbus_name.h"
#include "ut_constant.h"
#include "ut_utils_ext2.h"
#include "utils/ut_shapesutils_ext.h"
#include "utils/ut_delaytime.h"
#include "widgets/ut_previewwidget.h"
// --- 覆盖率提升：utils _cov.h（须在对应 base 头之后）---
#include "utils/ut_audioutils_cov.h"
#include "utils/ut_baseutils_cov.h"
#include "utils/ut_borderprocessinterface_cov.h"
#include "utils/ut_configsettings_cov.h"
#include "utils/ut_dbusutils_cov.h"
#include "utils/ut_pixmergethread_cov.h"
#include "utils/ut_screengrabber_cov.h"
#include "utils/ut_shortcut_cov.h"
#include "utils/ut_tempfile_cov.h"
#include "utils/ut_voicevolumewatcher_cov.h"
#include "utils/ut_x_multi_screen_info_cov.h"
// --- 覆盖率提升：ext-image-capture _cov.h（须在对应 base 头之后）---
#include "ext-image-capture/ut_extcaptureframebuffer_cov.h"
#include "ext-image-capture/ut_extcapturerecorder_cov.h"
#include "ext-image-capture/ut_extcaptureframe_cov.h"
#include "ext-image-capture/ut_extcapturesession_cov.h"
#include "ext-image-capture/ut_extcaptureintegration_cov.h"
#include "ext-image-capture/ut_extcapturemanager_cov.h"
#include "ext-image-capture/ut_extoutputsourcemanager_cov.h"
#include "ext-image-capture/ut_multiscreencapturecoordinator_cov.h"
#include "ext-image-capture/ut_multiscreenframecompositor_cov.h"
#include "ext-image-capture/ut_extcapturebridge_cov.h"
#include "ext-image-capture/ut_extcapturerecorder_ffmpeg_cov.h"
#include "ext-image-capture/ut_extcaptureframe_run_cov.h"
// --- 覆盖率提升：widgets / 顶层 / 子目录 _cov.h ---
#include "ut_smallfiles_cov.h"
#include "ut_main_window_cov2.h"
#include "ut_main_window_cov3.h"
#include "ut_capture_cov.h"
#include "ut_dbusscreenshotservice_cov.h"
#include "ut_protocols_cov.h"
#include "ut_record_process_cov2.h"
#include "ut_capture_recordprocess_screengrabber_cov3.h"
#include "ut_utils_cov2.h"
#include "ut_screenshot_cov2.h"
#include "ut_RecorderRegionShow_cov2.h"
#include "widgets/ut_shapeswidget_cov2.h"
#include "widgets/ut_subtoolwidget_cov2.h"
#include "widgets/ut_toolbar_cov2.h"
#include "widgets/ut_toolbutton_cov2.h"
#include "widgets/ut_camerawidget_cov2.h"
#include "widgets/ut_filter_cov2.h"
#include "widgets/ut_savemenumanager_cov2.h"
#include "widgets/ut_shottoolwidget_cov2.h"
#include "widgets/ut_shapeswidget_subtoolwidget_cov3.h"
#include "gstrecord/ut_gstrecordx_cov2.h"
#include "ext-image-capture/ut_ext_capture_cov2.h"
#include "widgets/ut_savebutton_cov.h"
#include "widgets/ut_savemenumanager_cov.h"
#include "widgets/ut_toolbutton_cov.h"
#include "widgets/ut_sidebar_cov.h"
#include "widgets/ut_subtoolwidget_cov.h"
#include "widgets/ut_shottoolwidget_cov.h"
#include "widgets/ut_imagemenu_cov.h"
#include "widgets/ut_toolbar_cov.h"
#include "widgets/ut_tooltips_cov.h"
#include "ut_record_process_cov.h"
#include "ut_utils_cov.h"
#include "ut_countdown_tooltip_cov.h"
#include "ut_show_buttons_cov.h"
#include "ut_recordertablet_cov.h"
#include "menucontroller/ut_menucontroller_cov.h"
#include "ut_camera_cov.h"
#include "dbusinterface/ut_dbusinterface_cov.h"
#include "ut_misc_cov2.h"
#include "ut_resid_cov.h"
//#include "ut_protocols_extimg_cov2.h"  // ACCESS_PRIVATE_STATIC_FUN macro can't handle QtWayland:: namespaced classes
// ut_wayland_stub.h: Qt 的 QWaylandClientExtension 生成的 wrapper 方法在 manager
// 未绑定真实合成器时于 Qt6Core 内部 SEGV(T3)，宏守卫+wl 桩均无法绕过，已禁用。

