/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p com_deepin_daemon_audio_sink com.deepin.daemon.Audio.Sink.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "com_deepin_daemon_audio_sink.h"

/*
 * Implementation of interface class ComDeepinDaemonAudioSinkInterface
 */

ComDeepinDaemonAudioSinkInterface::ComDeepinDaemonAudioSinkInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComDeepinDaemonAudioSinkInterface::~ComDeepinDaemonAudioSinkInterface()
{
}

