/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p utils_interface -c utils_interface ./com.deepin.daemon.Audio.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "utils_interface.h"
#include "utils/log.h"

/*
 * Implementation of interface class utils_interface
 */

utils_interface::utils_interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qCDebug(dsrApp) << "utils_interface initialized for service:" << service << ", path:" << path;
}

utils_interface::~utils_interface()
{
    qCDebug(dsrApp) << "utils_interface destructor called.";
}

