name: 储存逻辑-自定义路径包含含特殊字符
app: deepin-screen-recorder
module: 截图录屏/设置
feature: 自定义路径
tags:
- L2
vars:
  xlsx_id: '1915749'
  case_type: 功能测试
description: '前置条件: 1. 截图工具已安装并启动 2.桌面存在测试文件夹，名称为tes!@#^&文件夹222

  测试步骤:

  1. 保存方式设置为每次询问，完成截图后点击保存

  2. 选择测试文件夹（tes!@#^&文件夹222），点击保存

  3. 保存方式设置为保存时更新位置，完成截图后点击保存

  4. 选择测试文件夹（tes!@#^&文件夹222），点击保存

  预期结果:

  1. 弹出文管的选择窗口

  2. 截图成功，切换至该路径可查看到截图文件

  3. 弹出文管的选择窗口

  4. 截图成功，切换至该路径可查看到截图文件

  '
steps: []
teardown: []
skip: 创建含特殊字符的测试文件夹
setup: []
