name: 储存逻辑-已截图保存在指定位置-smb/ftp/sftp
app: deepin-screen-recorder
module: 截图录屏/设置
feature: 指定位置
tags:
- L2
vars:
  xlsx_id: '1915735'
  case_type: 功能测试
description: '前置条件: 1. 截图工具已安装并启动 2.保存方式设置为-smb/ftp/sftp

  测试步骤:

  1. 框选任意区域，点击保存按钮

  预期结果:

  1. smb/ftp/sftp内新增截图文件

  '
steps: []
skip: 跳过-需要特殊硬件或网络环境
setup: []
teardown: []
