name: REUSE Compliance Check

on:
  pull_request_target:
    paths-ignore:
      - ".github/workflows/**"
      - "3rdparty/**"          # 忽略整个 3rdparty 目录
      - "3rdparty/libcam/**"   # 或者具体忽略某个子目录
      - "3rdparty/googletest/**"
      - "3rdparty/stub_linux/**"

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      
      - name: REUSE Compliance Check
        run: |
          pip3 install reuse
          reuse lint --suppress-deprecation
